# 使用官方的OpenJDK 17镜像作为基础镜像
##  docker pull maven:3.8-openjdk-17-slim
FROM maven:3.8-openjdk-17-slim

## 创建工作目录
WORKDIR /app

## 将源代码复制到工作目录
COPY . /app/

## 打包源代码
RUN mvn package

# 指定容器启动时运行的命令
# CMD ["java", "-jar", "/app/bootstrap/target/muagent-runtime.jar"]
CMD ["java", "-jar", "/app/bootstrap/muagent-runtime.jar"]