name: Docker Image CI Test

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-20.04  # 或者指定其他版本
    strategy:
      matrix:
        image: 
          - name: runtime
            context: ./runtime
            dockerfile: ./runtime/Dockerfile.no-package
            tag: ghcr.io/codefuse-ai/runtime:0.1.0
          - name: ekgfrontend
            context: .
            dockerfile: ./Dockerfile_frontend
            tag: ghcr.io/codefuse-ai/ekgfrontend:0.1.0
          - name: ekgservice
            context: .
            dockerfile: ./Dockerfile_gh
            tag: ghcr.io/codefuse-ai/ekgservice:0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用当前 GitHub 用户名
          password: ${{ secrets.CR_TOKEN }}  # 使用您刚刚添加的个人访问令牌

      - name: Check disk space
        run: df -h

      - name: Clean up Docker
        run: docker system prune -af

      - name: Check disk space
        run: df -h

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: ${{ matrix.image.tag }}
          platforms: |
            linux/amd64
            linux/arm64

      - name: Check disk space
        run: df -h