name: Docker Image CI Test

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用当前 GitHub 用户名
          password: ${{ secrets.CR_TOKEN }}  # 使用您刚刚添加的个人访问令牌

      - name: show local dir
        run: |
            pwd
            ls -l
            ls -l ./runtime

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./runtime
          file: ./runtime/Dockerfile.no-package
          push: true
          tags: ghcr.io/codefuse-ai/runtime:0.1.0
          platforms: |
            linux/amd64
            linux/arm64

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile_frontend
      #     push: true
      #     tags: ghcr.io/lightislost/ekgfrontend:latest
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
